### PR TITLE
Error: string "cryptokitties" exceeds maximum length of 10. Fixed.

### PR DESCRIPTION
**Pull request by svanas**

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@svanas 

Thank you. Can you please redo this commit with only the fix and not all of the spacing updates? Or consolidate the spacing updates to a different commit? This will make it easier to review the PR.

**Review by wbnns — APPROVED** [review]
Thanks!

**Comment by svanas** [comment]
@wbnns Thank you for merging. Can you re-publish to wrapped.tokensoft.eth? Thanks!

**Comment by wbnns** [comment]
Yep! Cc: @masonicGIT

**Pull request merged**
